# 데이터 소스
spring:
  datasource:
    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/board?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root

# 정적 파일 변경 실시간 반영
  devtools:
    restart:
      enabled: 'false'
    livereload:
      enabled: 'true'

# 타임리프 캐싱 OFF
  thymeleaf:
    cache: 'false'

# JPA 설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: 'false'
    show-sql: 'true'
    open-in-view: 'false'
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
        use_sql_comments: 'true'
        default_batch_fetch_size: '100'