spring: 
  datasource: 
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    
  jpa: 
    hibernate: 
      ddl-auto: none 
    properties: 
      hibernate: 
        format_sql: true
  mvc:
    hidden-method:
      filter:
        enabled: true
        
  devtools:
    livereload:
      enabled: true
    thymeleaf:
      cache: false
    restart:
      enable: false

  logging:
    level:
      org.hibernate.SQL: debug
      
  upload:
    path: C:\Users\k0106\JavaSpringboot\study\file 

  
  servlet:
    muoltipart:
      max-file-size: 10MB
      max-request-sizd: 10MB